-- Generated by Oracle SQL Developer Data Modeler 3.1.4.710
--   at:        2015-04-09 20:14:11 EDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE ARTIST 
    ( 
     ID INTEGER  NOT NULL , 
     NAME VARCHAR2 (100 CHAR) , 
     EMAIL VARCHAR2 (100 CHAR) , 
     TITLE VARCHAR2 (100 CHAR) , 
     SALARY NUMBER (10,2) 
    ) 
    LOGGING 
;



ALTER TABLE ARTIST 
    ADD CONSTRAINT ARTIST_PK PRIMARY KEY ( ID ) ;



CREATE TABLE CUSTOMER 
    ( 
     ID INTEGER  NOT NULL , 
     NAME VARCHAR2 (100 CHAR) , 
     EMAIL VARCHAR2 (100 CHAR) , 
     PHONE VARCHAR2 (15 CHAR) , 
     ADDRESS VARCHAR2 (200 CHAR) , 
     CITY VARCHAR2 (100 CHAR) , 
     STATE VARCHAR2 (50 CHAR) , 
     ZIP VARCHAR2 (10 CHAR) , 
     CREDIT_CARD_NUMBER VARCHAR2 (30 CHAR) 
    ) 
    LOGGING 
;



ALTER TABLE CUSTOMER 
    ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY ( ID ) ;



CREATE TABLE DESIGN 
    ( 
     ID INTEGER  NOT NULL , 
     ARTIST_ID INTEGER  NOT NULL , 
     COST_TO_SELL NUMBER (10,2) , 
     COST_TO_MAKE NUMBER (10,2) , 
     MATERIAL VARCHAR2 (255 CHAR) 
    ) 
    LOGGING 
;



ALTER TABLE DESIGN 
    ADD CONSTRAINT DESIGN_PK PRIMARY KEY ( ID ) ;



CREATE TABLE ORDERS 
    ( 
     ID INTEGER  NOT NULL , 
     SUPPLIER_ID INTEGER  NOT NULL , 
     CUSTOMER_ID INTEGER  NOT NULL , 
     AMOUNT NUMBER (10,2) , 
     QUANTITY INTEGER , 
     DATE_CREATED DATE , 
     CONFIRMATION_NUMBER INTEGER 
    ) 
    LOGGING 
;



ALTER TABLE ORDERS 
    ADD CONSTRAINT ORDER_PK PRIMARY KEY ( ID ) ;



CREATE TABLE SPECIAL 
    ( 
     ID INTEGER  NOT NULL , 
     QUARTER_OFFERED VARCHAR2 (200 CHAR) , 
     PRICE_REDUCTION NUMBER (10,2) , 
     DESIGN VARCHAR2 (200 CHAR) , 
     ARTIST VARCHAR2 (200) , 
     MATERIAL VARCHAR2 (200 CHAR) 
    ) 
    LOGGING 
;



ALTER TABLE SPECIAL 
    ADD CONSTRAINT SPECIAL_PK PRIMARY KEY ( ID ) ;



CREATE TABLE SUPPLIER 
    ( 
     ID INTEGER  NOT NULL , 
     DESIGN_ID INTEGER  NOT NULL , 
     SPECIAL_ID INTEGER  NOT NULL , 
     NAME VARCHAR2 (100 CHAR) , 
     ADDRESS VARCHAR2 (255 CHAR) , 
     CITY VARCHAR2 (100 CHAR) , 
     STATE VARCHAR2 (50 CHAR) , 
     MATERIAL_SUPPLIED VARCHAR2 (150 CHAR) 
    ) 
    LOGGING 
;



ALTER TABLE SUPPLIER 
    ADD CONSTRAINT SUPPLIER_PK PRIMARY KEY ( ID ) ;




ALTER TABLE DESIGN 
    ADD CONSTRAINT DESIGN_ARTIST_FK FOREIGN KEY 
    ( 
     ARTIST_ID
    ) 
    REFERENCES ARTIST 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE ORDERS 
    ADD CONSTRAINT ORDER_CUSTOMER_FK FOREIGN KEY 
    ( 
     CUSTOMER_ID
    ) 
    REFERENCES CUSTOMER 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE ORDERS 
    ADD CONSTRAINT ORDER_SUPPLIER_FK FOREIGN KEY 
    ( 
     SUPPLIER_ID
    ) 
    REFERENCES SUPPLIER 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE SUPPLIER 
    ADD CONSTRAINT SUPPLIER_DESIGN_FK FOREIGN KEY 
    ( 
     DESIGN_ID
    ) 
    REFERENCES DESIGN 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE SUPPLIER 
    ADD CONSTRAINT SUPPLIER_SPECIAL_FK FOREIGN KEY 
    ( 
     SPECIAL_ID
    ) 
    REFERENCES SPECIAL 
    ( 
     ID
    ) 
    NOT DEFERRABLE 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
